### PR TITLE
Add eiga.com

### PR DESCRIPTION
**Pull request by locoda**
Thank you for writing this extension and it is really useful for me to download images from websites 😄 

I am trying to add support to `eiga.com` in this PR. 

This is my first time writing chrome extension, so do not hesitate to modify my code or suggest if I did anything wrong.

### CODE REVIEW

**Comment by shoushouminami** [comment]
@locoda 

Nice job! Thanks for contributing!

The change looks good. 

One test file might fail: `sites.test.js`. Do you mind fixing it? You can check my previous changes like https://github.com/shoushouminami/modelpress-downloader/commit/41e9c0035840813b0a440e58654b721c6ac68cc6#diff-1aa8f447e65ee6c1d5df228b6a427d37b7caabd7d7d3d72c67efde250f7b4d17

You can run individual test files with jest (assuming you have environment setup. If not, just do `npm ci` to install all build dependencies)
```
npx jest test/inject/sites.test.js
```

**Comment by locoda** [comment]
Just update the commit to fix that test. 😆

**Comment by shoushouminami** [comment]
@locoda Thank you.

**Comment by shoushouminami** [comment]
It will be released in the next version. Hopefully in a few days.

**Comment by locoda** [comment]
@shoushouminami Thanks you for doing this :) I'll also try to add more if I spot new sites that is not supported

**Pull request merged**
